using module "..\CAMP.psm1"

class markdown : CAMPOutput {

    $OutputDirectory = $null

    markdown() {
        $this.Name = "Markdown"
    }

    RunOutput($Checks, $Collection) {

        if ($null -eq $this.OutputDirectory) {
            $OutputDir = $this.DefaultOutputDirectory
        }
        else {
            $OutputDir = $this.OutputDirectory
        }

        $Tenant = $(($Collection["AcceptedDomains"] | Where-Object { $_.InitialDomain -eq $True }).DomainName -split '\.')[0]
        $ReportFileName = "CAMP-$($Tenant)-$(Get-Date -Format 'yyyyMMddHHmm').md"
        $OutputFile = Join-Path $OutputDir $ReportFileName

        $TenantDomain = ($Collection["AcceptedDomains"] | Where-Object { $_.InitialDomain -eq $True }).DomainName
        $ReportDate = "$(Get-Date -format 'dd-MMM-yyyy HH:mm') $($(Get-TimeZone).Id)"

        $sb = [System.Text.StringBuilder]::new()

        [void]$sb.AppendLine("# CAMP — Configuration Analyzer for Microsoft Purview")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("**Tenant:** $TenantDomain  ")
        [void]$sb.AppendLine("**Report date:** $ReportDate  ")
        [void]$sb.AppendLine("**Total checks evaluated:** $($Checks.Count)  ")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("> This report is generated by CAMP, a strictly read-only diagnostic. No tenant configuration was modified.")
        [void]$sb.AppendLine()

        # --- Headline counters ---
        $Pass = @($Checks | Where-Object { $_.Result -eq "Pass" }).Count
        $Fail = @($Checks | Where-Object { $_.Result -eq "Fail" }).Count
        $Info = @($Checks | Where-Object { $_.Result -eq "Recommendation" }).Count
        $Unavail = @($Checks | Where-Object { $_.Completed -eq $false }).Count

        [void]$sb.AppendLine("## Overall summary")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("| ✅ Pass | ⚠️ Recommendation | ❌ Improvement | ⏭️ Not assessed |")
        [void]$sb.AppendLine("|--------|-------------------|----------------|-----------------|")
        [void]$sb.AppendLine("| $Pass | $Info | $Fail | $Unavail |")
        [void]$sb.AppendLine()

        # --- Blueprint maturity scorecard ---
        [void]$sb.AppendLine("## Microsoft Purview Deployment Model maturity scorecard")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("| Blueprint | Good | Better | Best | Status |")
        [void]$sb.AppendLine("|-----------|------|--------|------|--------|")

        $BlueprintOrder = @(
            @{ Flag = [CAMPBlueprint]::SecureByDefault;      Label = "Secure by Default" }
            @{ Flag = [CAMPBlueprint]::LightweightDLP;       Label = "Lightweight DLP" }
            @{ Flag = [CAMPBlueprint]::ShadowAI;             Label = "Prevent data leak to shadow AI" }
            @{ Flag = [CAMPBlueprint]::CopilotAgents;        Label = "Secure & govern Microsoft 365 Copilot agents" }
            @{ Flag = [CAMPBlueprint]::DSPM;                 Label = "Data Security Posture Management" }
            @{ Flag = [CAMPBlueprint]::ReduceFalsePositives; Label = "Reduce false positives" }
        )

        foreach ($bp in $BlueprintOrder) {
            $BpChecks = @($Checks | Where-Object {
                $_.Blueprint -ne [CAMPBlueprint]::None -and
                ($_.Blueprint -band $bp.Flag) -eq $bp.Flag -and
                $_.Completed -eq $true
            })
            if ($BpChecks.Count -eq 0) {
                [void]$sb.AppendLine("| $($bp.Label) | — | — | — | _no checks_ |")
                continue
            }

            $GoodAll = @($BpChecks | Where-Object { $_.MaturityLevel -eq [CAMPMaturityLevel]::Good })
            $BetterAll = @($BpChecks | Where-Object { $_.MaturityLevel -eq [CAMPMaturityLevel]::Better })
            $BestAll = @($BpChecks | Where-Object { $_.MaturityLevel -eq [CAMPMaturityLevel]::Best })
            $GoodPass = @($GoodAll | Where-Object { $_.Result -eq "Pass" }).Count
            $BetterPass = @($BetterAll | Where-Object { $_.Result -eq "Pass" }).Count
            $BestPass = @($BestAll | Where-Object { $_.Result -eq "Pass" }).Count

            $GoodCell = if ($GoodAll.Count -gt 0) { "$GoodPass / $($GoodAll.Count)" } else { "—" }
            $BetterCell = if ($BetterAll.Count -gt 0) { "$BetterPass / $($BetterAll.Count)" } else { "—" }
            $BestCell = if ($BestAll.Count -gt 0) { "$BestPass / $($BestAll.Count)" } else { "—" }

            $TotalPass = $GoodPass + $BetterPass + $BestPass
            $TotalCount = $BpChecks.Count
            $StatusIcon = if ($TotalPass -eq $TotalCount) { "✅" }
                          elseif ($TotalPass -ge ([Math]::Ceiling($TotalCount * 0.5))) { "⚠️" }
                          else { "❌" }
            $StatusCell = "$StatusIcon $TotalPass / $TotalCount"

            [void]$sb.AppendLine("| $($bp.Label) | $GoodCell | $BetterCell | $BestCell | $StatusCell |")
        }

        [void]$sb.AppendLine()
        [void]$sb.AppendLine("_Good / Better / Best maps to the Microsoft Purview Lightweight DLP maturity model (each cell shows passing checks / total checks at that level)._")
        [void]$sb.AppendLine()

        # --- Solutions summary (legacy view) ---
        [void]$sb.AppendLine("## Solutions summary")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("| Area | ✅ Pass | ⚠️ Recommendation | ❌ Improvement |")
        [void]$sb.AppendLine("|------|--------|-------------------|----------------|")
        foreach ($area in ($Checks | Where-Object { $_.Completed -eq $true } | Group-Object Area | Sort-Object Name)) {
            $p = @($area.Group | Where-Object { $_.Result -eq "Pass" }).Count
            $f = @($area.Group | Where-Object { $_.Result -eq "Fail" }).Count
            $i = @($area.Group | Where-Object { $_.Result -eq "Recommendation" }).Count
            [void]$sb.AppendLine("| $($area.Name) | $p | $i | $f |")
        }
        [void]$sb.AppendLine()

        # --- Per-check detail grouped by Parent Area ---
        [void]$sb.AppendLine("## Findings")
        [void]$sb.AppendLine()

        foreach ($parent in ($Checks | Where-Object { $_.Completed -eq $true } | Group-Object ParentArea | Sort-Object Name)) {
            [void]$sb.AppendLine("### $($parent.Name)")
            [void]$sb.AppendLine()

            foreach ($check in ($parent.Group | Sort-Object -Property @{Expression='Result';Descending=$true}, @{Expression='Control';Descending=$false})) {
                $icon = switch ($check.Result.ToString()) {
                    "Pass" { "✅" }
                    "Recommendation" { "⚠️" }
                    "Fail" { "❌" }
                    default { "•" }
                }
                [void]$sb.AppendLine("#### $icon $($check.Control) — $($check.Name)")
                [void]$sb.AppendLine()
                if ($check.Result.ToString() -eq "Pass") {
                    [void]$sb.AppendLine("**$($check.PassText)**")
                } else {
                    [void]$sb.AppendLine("**$($check.FailRecommendation)**")
                }
                [void]$sb.AppendLine()
                if ($check.Importance) {
                    [void]$sb.AppendLine($check.Importance)
                    [void]$sb.AppendLine()
                }

                if ($check.Config.Count -gt 0) {
                    [void]$sb.AppendLine("| Object | $(if($check.ItemName){$check.ItemName}else{'Item'}) | $(if($check.DataType){$check.DataType}else{'Data'}) | Status |")
                    [void]$sb.AppendLine("|--------|------|------|--------|")
                    foreach ($cfg in $check.Config) {
                        $levelIcon = switch ($cfg.Level.ToString()) {
                            "Ok" { "✅" }
                            "Recommendation" { "⚠️" }
                            "Informational" { "ℹ️" }
                            default { "•" }
                        }
                        $obj = if ($cfg.Object) { ($cfg.Object -replace '<[^>]+>','' -replace '\|','\|') } else { "" }
                        $item = if ($cfg.ConfigItem) { ($cfg.ConfigItem -replace '\|','\|') } else { "" }
                        $data = if ($cfg.ConfigData) { ($cfg.ConfigData -replace '\|','\|') } else { "" }
                        [void]$sb.AppendLine("| $obj | $item | $data | $levelIcon |")
                    }
                    [void]$sb.AppendLine()
                }

                if ($null -ne $check.Links -and $check.Links.Count -gt 0) {
                    [void]$sb.AppendLine("**Learn more:**")
                    foreach ($key in $check.Links.Keys) {
                        [void]$sb.AppendLine("- [$key]($($check.Links[$key]))")
                    }
                    [void]$sb.AppendLine()
                }
            }
        }

        # --- Unavailable checks ---
        $UnavailChecks = @($Checks | Where-Object { $_.Completed -eq $false })
        if ($UnavailChecks.Count -gt 0) {
            [void]$sb.AppendLine("## Checks not assessed")
            [void]$sb.AppendLine()
            [void]$sb.AppendLine("These checks did not run, typically because the required data source was unavailable (Microsoft.Graph not installed, sovereign cloud lacks the feature, tenant lacks the license, etc.).")
            [void]$sb.AppendLine()
            [void]$sb.AppendLine("| Control | Name | Reason |")
            [void]$sb.AppendLine("|---------|------|--------|")
            foreach ($check in ($UnavailChecks | Sort-Object Control)) {
                $reason = if ($check.UnavailableReason) { $check.UnavailableReason } else { "Required data source unavailable." }
                $reason = $reason -replace '\|','\|'
                [void]$sb.AppendLine("| $($check.Control) | $($check.Name) | $reason |")
            }
            [void]$sb.AppendLine()
        }

        $sb.ToString() | Out-File -FilePath $OutputFile -Encoding UTF8

        $this.Completed = $true
        $this.Result = $OutputFile
    }
}
